CREATE DATABASE PLANILLAS;
USE PLANILLAS;


CREATE TABLE [ROLES] (
    ID_ROL INT IDENTITY(1,1)    NOT NULL,
    NOMBRE VARCHAR(50)          NOT NULL,
    ESTADO BIT                  NOT NULL,
    
    CONSTRAINT PK_ROLES_ID_ROL PRIMARY KEY (ID_ROL)
);
INSERT INTO ROLES(NOMBRE, ESTADO) VALUES('Administrador', 1);


CREATE TABLE EVENTOS (
    ID_EVENTO   INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION VARCHAR(50),

    CONSTRAINT PK_EVENTOS_ID_EVENTO PRIMARY KEY (ID_EVENTO)
);


CREATE TABLE MUNICIPIOS (
    ID_MUNICIPIO    INT IDENTITY(1,1)   NOT NULL,
    DESCRIPCION     VARCHAR(50)         NOT NULL,

    CONSTRAINT PK_MUNICIPIOS_ID_MUNICIPIO PRIMARY KEY (ID_MUNICIPIO)
);


CREATE TABLE GENERO (
    ID_GENERO   INT IDENTITY(1,1)   NOT NULL,
    DESCRIPCION VARCHAR(50)         NOT NULL,

    CONSTRAINT PK_GENERO_ID_GENERO PRIMARY KEY (ID_GENERO)
);
INSERT INTO GENERO(DESCRIPCION) VALUES('Masculino');
INSERT INTO GENERO(DESCRIPCION) VALUES('Femenino');


CREATE TABLE POSICION (
    ID_POSICION INT IDENTITY(1,1)   NOT NULL,
    DESCRIPCION VARCHAR(50)         NOT NULL,

    CONSTRAINT PK_POSICION_ID_POSICION PRIMARY KEY (ID_POSICION)
);
INSERT INTO POSICION(DESCRIPCION) VALUES('Gerente');


CREATE TABLE [EMPLEADOS] (
    ID_EMPLEADO         INT IDENTITY(1,1)   NOT NULL,
    CODIGO              VARCHAR(50)         NOT NULL,
    NOMBRE              VARCHAR(100)        NOT NULL,
    APELLIDO            VARCHAR(100)        NOT NULL,
    FECHA_INGRESO       DATE                NOT NULL, 
    FECHA_NACIMIENTO    DATE                NOT NULL,
    DIRECCION           VARCHAR(200)        NOT NULL,
    EMAIL               VARCHAR(50)         NOT NULL,
    TELEFONO            VARCHAR(50)         NOT NULL,
    SALARIO             DECIMAL(8,2)        NOT NULL,
    ESTADO              BIT                 NOT NULL,
    ID_POSICION         INT                 NOT NULL,
    ID_MUNICIPIO        INT                 NOT NULL,
    ID_GENERO           INT                 NOT NULL,

    CONSTRAINT PK_EMPLEADOS_ID_EMPLEADO PRIMARY KEY (ID_EMPLEADO)
);
ALTER TABLE EMPLEADOS ADD FOREIGN KEY (ID_POSICION) REFERENCES POSICION (ID_POSICION);
ALTER TABLE EMPLEADOS ADD FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIOS (ID_MUNICIPIO);
ALTER TABLE EMPLEADOS ADD FOREIGN KEY (ID_GENERO) REFERENCES GENERO (ID_GENERO);


CREATE TABLE USUARIOS (
    ID_USUARIO      INT IDENTITY(1,1)   NOT NULL,
    NOMBRE          VARCHAR(50)         NOT NULL,
    CONTRASENIA     VARCHAR(250)        NOT NULL,
    IMAGEN          VARBINARY(MAX),
    ESTADO          BIT                 NOT NULL,
    ID_EMPLEADO     INT                 NOT NULL,
    ID_ROL          INT                 NOT NULL,

    CONSTRAINT PK_USUARIOS_ID_USUARIO PRIMARY KEY (ID_USUARIO)
);
ALTER TABLE USUARIOS ADD FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO);
ALTER TABLE USUARIOS ADD FOREIGN KEY (ID_ROL) REFERENCES ROLES (ID_ROL);


CREATE TABLE BITACORA (
    ID_BITACORA     INT IDENTITY(1,1)   NOT NULL,
    FECHA           DATE                NOT NULL,
    ORIGEN          VARCHAR(100)        NOT NULL,
    MONTO           DECIMAL(10,2)       NOT NULL,
    DESCRIPCION     VARCHAR(200),
    ESTADO          BIT                 NOT NULL,
    ID_EVENTO       INT                 NOT NULL,
    ID_EMPLEADO     INT                 NOT NULL,
	TIPO            BIT                 NOT NULL,

    CONSTRAINT PK_BITACORA_ID_BITACORA PRIMARY KEY (ID_BITACORA)
);
ALTER TABLE BITACORA ADD FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS (ID_EVENTO);
ALTER TABLE BITACORA ADD FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO);


CREATE TABLE PLANILLA (
    ID_PLANILLA INT IDENTITY(1,1)   NOT NULL,
    ESTADO      BIT                 NOT NULL,
    FECHA       DATE                NOT NULL,   
	TOTAL       DECIMAL(10,2)       NOT NULL,

    CONSTRAINT PK_PLANILLA_ID_PLANILLA PRIMARY KEY (ID_PLANILLA)
);


CREATE TABLE PLANILLA_DETALLE (
	ID_DETALLE          INT IDENTITY(1,1)   NOT NULL,
	DIAS_LABO           INT                 NOT NULL,
    HORAS_EXTRA         INT,
    SUBTOTAL            DECIMAL(8,2)        NOT NULL,
    BONIFICACIONES      DECIMAL(8,2),
	DESCUENTOS          DECIMAL(8,2)        NOT NULL,
    TOTAL_DEVENGADO     DECIMAL(8,2)        NOT NULL,
    ISSS                DECIMAL(8,2)        NOT NULL,
    AFP                 DECIMAL(8,2)        NOT NULL,
    ISR                 DECIMAL(8,2)        NOT NULL,
    TOTAL_DESCUENTO     DECIMAL(8,2)        NOT NULL,
    LIQUIDO             DECIMAL(8,2)        NOT NULL,
    ID_EMPLEADO         INT                 NOT NULL,
	ID_PLANILLA         INT                 NOT NULL,

	CONSTRAINT PK_PLANILLA_DETALLE_ID_DETALLE PRIMARY KEY(ID_DETALLE)
);
ALTER TABLE PLANILLA_DETALLE ADD FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO);
ALTER TABLE PLANILLA_DETALLE ADD FOREIGN KEY (ID_PLANILLA) REFERENCES PLANILLA(ID_PLANILLA);



INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Ahuachapan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Apaneca');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Atiquizaya');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Concepcion de Ataco');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Refugio');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Guaymango');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Jujutla');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Francisco Menendez');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Lorenzo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Pedro Puxtla');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Tacuba');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Turin');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Cinquera');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Dolores');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Guacotecti');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Ilobasco');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Jutiapa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Isidro');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Sensuntepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Tejutepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Victoria');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Agua Caliente');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Arcatao');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Azacualpa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Chalatenango');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Comalapa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Citala');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Concepcion Quezaltepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Dulce Nombre de Maria');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Carrizal');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Paraiso');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('La Laguna');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('La Palma');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('La Reina');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Las Vueltas');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Nueva Concepcion');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Nueva Trinidad');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Nombre de Jesus');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Ojos de Agua');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Potonico');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Antonio de la Cruz');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Antonio Los Ranchos');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Fernando');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Francisco Lempa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Francisco Morazan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Ignacio');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Isidro Labrador');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Jose Cancasque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Jose Las Flores');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Luis del Carmen');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Miguel de Mercedes');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Rafael');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Rita');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Tejutla');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Candelaria');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Cojutepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Carmen');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Rosario');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Monte San Juan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Oratorio de Concepcion');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Bartolome Perulapia');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Cristobal');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Jose Guayabal');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Pedro Perulapan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Rafael Cedros');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Ramon');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Cruz Analquito');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Cruz Michapa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Suchitoto');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Tenancingo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Antiguo Cuscatlan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Chiltiupan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Ciudad Arce');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Colon');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Comasagua');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Huizucar');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Jayaque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Jicalapa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('La Libertad');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Tecla');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Nuevo Cuscatlan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Juan Opico');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Quezaltepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Sacacoyo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Jose Villanueva');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Matias');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Pablo Tacachico');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Talnique');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Tamanique');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Teotepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Tepecoyo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Zaragoza');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Cuyultitan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Rosario');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Jerusalen ');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Mercedes La Ceiba');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Olocuilta');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Paraiso de Osorio');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Antonio Masahuat');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Emigdio');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Francisco Chinameca');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Juan Nonualco');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Juan Talpa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Juan Tepezontes');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Luis Talpa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Luis La Herradura');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Miguel Tepezontes');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Pedro Masahuat');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Pedro Nonualco');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Rafael Obrajuelo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Maria Ostuma');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santiago Nonualco ');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Tapalhuaca');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Zacatecoluca');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Anamoros');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Bolivar ');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Concepcion de Oriente');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Conchagua');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Carmen');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Sauce');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Intipuca');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('La Union');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Lislique');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Meanguera del Golfo ');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Nueva Esparta');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Pasaquina');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Poloros');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Alejo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Jose');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Rosa de Lima');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Yayantique');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Yucuaiquin');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Arambala');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Cacaopera');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Chilanga');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Corinto ');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Delicias de Concepcion');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Divisadero');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Rosario');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Gualococti');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Guatajiagua');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Joateca');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Jocoaitique');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Jocoro');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Lolotiquillo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Meanguera');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Osicala');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Perquin');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Carlos');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Fernando');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Francisco Gotera');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Isidro');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Simon');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Sensembra');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Sociedad');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Torola');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Yamabal');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Yoloaiquin');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Carolina');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Chapeltique');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Chinameca');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Chirilagua');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Ciudad Barrios');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Comacaran');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Transito');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Lolotique');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Moncagua');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Nueva Guadalupe');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Nuevo Eden de San Juan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Quelepa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Antonio del Mosco');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Gerardo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Jorge');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Luis de la Reina');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Miguel');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Rafael Oriente');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Sesori');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Uluazapa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Aguilares');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Apopa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Ayutuxtepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Cuscatancingo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Ciudad Delgado');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Paisnal');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Guazapa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Ilopango');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Mejicanos');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Nejapa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Panchimalco');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Rosario de Mora');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Marcos');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Martin');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Salvador');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santiago Texacuangos');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santo Tomas');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Soyapango');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Tonacatepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Apastepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Guadalupe');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Cayetano Istepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Esteban Catarina');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Ildefonso');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Lorenzo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Sebastian');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Vicente');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Clara');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santo Domingo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Tecoluca');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Tepetitan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Verapaz');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Candelaria de la Frontera');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Chalchuapa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Coatepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Congo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Porvenir');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Masahuat');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Metapan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Antonio Pajonal');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Sebastian Salitrillo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Ana');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Rosa Guachipilin');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santiago de la Frontera');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Texistepeque');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Acajutla');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Armenia');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Caluco');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Cuisnahuat');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Izalco');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Juayua');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Nahuizalco');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Nahulingo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Salcoatitan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Antonio del Monte');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Julian');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Catarina Masahuat');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Isabel Ishuatan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santo Domingo Guzman');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Sonsonate');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Sonzacate');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Alegria');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Berlin');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('California');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Concepcion Batres');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('El Triunfo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Ereguayquin');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Estanzuelas');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Jiquilisco');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Jucuapa');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Jucuaran');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Mercedes Umaña');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Nueva Granada');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Ozatlan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Puerto El Triunfo');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Agustin');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Buenaventura');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Dionisio');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('San Francisco Javier');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Elena');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santa Maria');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Santiago de Maria');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Tecapan');
INSERT INTO MUNICIPIOS(DESCRIPCION) VALUES ('Usulutan');
